/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "bsp.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	BSP_init();
	BSP_led_init();
	BSP_Timer_init();
	BSP_UART_init();

	uint32_t last_blink = 0;
	uint32_t last_uart = 0;

	while(1) {
		uint32_t current_time = BSP_getTick(); //gets curreent time
		if((current_time - last_blink)>=0) {
			BSP_led_Toggle();
			last_blink = current_time;
		}
		if((current_time - last_uart)>=0) {
			BSP_UART_init();
			last_uart = current_time;
		}
	}
}
